#!/usr/bin/env bash

PARAMS=""
VERBOSE=0
while (( "$#" )); do
  case $1 in
    -v|--verbose)
      VERBOSE=1
      shift
      ;;
    *) # Preserve any posiional arguments
      PARAMS="$PARAMS $1"
      shift;
      ;;
  esac
done

cd $MTI_REPO_DIR
for d in $(ls -d *)
do
  if [ $(cd $d; current_branch) != "develop" ]; then
    echo "  - { name: $d, branch: $(cd $d; current_branch) }"
  fi
done
if [[ $VERBOSE -gt 0 ]]
then
  echo "--Repositories on develop--"
  for d in $(ls -d *)
  do
    if [ $(cd $d; current_branch) == "develop" ]; then
      echo "  -  $d"
    fi
  done
fi